version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  chatbot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - NODE_TLS_REJECT_UNAUTHORIZED=0

    volumes:
      - ./docs:/app/docs
      - ./public:/app/public
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_data:
